language: node_js
node_js:
- 4
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2.4-precise
    - ubuntu-toolchain-r-test
    packages:
    - mongodb-org-server
    - gcc-4.8
    - g++-4.8
sudo: required
before_script: npm install
script:
- npm run test
- npm run lint
env:
  matrix:
  - CXX=g++-4.8
  - secure: Ztv1A9l8CKLDYOXrccE+W2ofxrkQrSznYeFdMKSxl6YlXSjOiG1UrAu6kLqJUWhwsh85AjwWxf9yKyECuvFEYafLlnREO7dbfbduDe0Y+6iysOLAkQvbCTixFodKn7ervnBVT3ieuo/2cEFBFVyECpeMLW83M9rB9TRXjxRtUdA0vjlILpZhq6th6K+j/YTDocbiIVx04RfM0xBGvu+4fGxF7w5Iqi3WBoyU7rVMHVgO0ud4yRON4pDIZY+iYi3MxqH4SZq8SHn28e/08iWLnpQQr/Ms5Y5ohMarsk3WnrMipZtBWSo4YQtlrQN84vADxsxob9pHGZXFTkUx5OvWW5D/fBCKK8zyyrA9vtGy54vD7dJ16flYZ/08WpZMqJJ743aTJkKDbotxG9UOYGhCP/RsQ1/XwVAFjTUmec5gQlrrq1SNf6ecYD6JINxPRmhGQTwduKRb6vnsdiUGIsQroeQ3ZWi2O3v4U6ewnLz1uJiK4IF/xx3eiU6orU7GjEC32t88kmC+rwVThZsFFzQ3TScaEoZ4o2d0aGhFxJJAcK02rOCpA5kKds1TuXD5PQW3LjUxb/0wkKlEljugrA5Q0zxxL3G2AOsBw9JGC/t0143FR3nlsvRYq6xgxVlOMRkKtruGG6/RO+RbKNPaARPxElfRYtWON+/jLm/DOMVTy8Y=
  - secure: FyxAM7GF8F+ahxmVLLnIltwLH3uer6Qb00Dt2APUilBIpFCBEQ74lXfLy/sAW8OjFN/wswLRCM6yTHYuKufQwPbCr3FpEdjEKEa0Z0+S12dC0lzFP6uIvZ76Sz95rNNFhsvCYCxkdRWB/7b7Ifg4bsWv0pYRst7DtCZx4TSs/VCCUUFz726GrB4nASQOYDJP1B/+jXovB75Kh9616Vd4evPFNRKJqUV3vlJly/5qljyGhgCkA979MY8XlvA9b7z1oUuXzN2BRnRxYfYmABLaQh+RUNWIYeJWwuP4BKz45HiFLah47ObTtn2LAuwtpab8OUa8YZn1ge9ywkwlRg47Bp5QFnyHHw+mZD33K26vEzJ1BbLo/Fk4iYOYPEQkeNgWb4WCAj9KagbHMzFqflP0DWmH9waTYvmeR7w+JyNllGIEsEjaf1DFD/dj8k9UDM7YLIXMK0Cvv55Q9YC4ujRoHv8RFwt6qFJYfsvdENNVNh5q8i9lQkXlvSriisOH9KMJoODelyKWhZwo0mi0HIroBy1JiDYmSEoXb7OUEkgd4LkEFvuChXShhoj/vusqJWA3puM0WGrA6wsi+3nkz2x2LTR9pEOWKXrnoxCj4UgWtin9h3vlduB+TBCLsKG68m2NhhbMIgrydxWnoSwDkHTbBn2C/SxtKlqPulzHf74U+ac=
  - secure: dZOjtfjOJPyrPNpnGV/ozr5ah7oR2twdiFptsxvFdhJauSFLK6w7UfWFSXNJSAmg0YeGWVkXCedw7RCdLWvCByajKlp5WmAcEjZ4q9opncTmGq2z4ongYVjimloPFrRD0SGyZTmik2KvH8jAP7qRVBjA4uBluEP5H0flFOA6kBOIp8IxvYfnh64lX5i7wZb7h6lGDt+9FNvJbcn6FC4jZC1ljAsjuE05McD1cDuSAo+TAKM6fs9x+7hn8SxVnOrCFe1GX7b6DZyDrLIm1zAZw8GFk1dNoe55femBY/ToW3WDlY/d/jX52NPausRLMn7LP71AaVrJblM3bAYScJjXk7442sZaUQJjRuL465+1msyqWMEAsjtj7CyFRtDmejvavl0s4qT9bYfVc+RoscaTVfXA/mzTpPk7A8XPxBJJKyrNw6cvfADJz/EOOhahqda6uPp/Fqyd2icigCvND4XteMB3lsVU5REuyZkSMtXSqQwR/iOZHrouUcW/dnxE1SjppvsgpXqu1KCHZ71L2WooClT06XGwZRrTzxQUJhJ5P9UnKgBlMIFQsEn9giWeBmJ+46x2l2TTifUsuoN7vbxyTHcZizeuK9WZgJo62pGVeMgO38DVczrlknIAEa7b3iWk+z9kGgpXECVaI0d0pJQQn8lFl9mECugew66nJ2ichxM=
  - secure: Dt34RqUw1LII6GlyVr4JYyQQHDn1xRY/3t7jKa0fCw0q4LBp3LYHOgcFqmkmwMPXZOAMZuvePhIi44/WSHwCN4pj/Wik6DqspV6M8VOMABubwRpNp38pusyZBVgbaNQ96Wo7B8wY4kCtO0oT/Fgyx4k9fuZ9uqqBOm5nfLElNOFX/AN6SxEaA9TC7LqmH/lWFEVF9Hzhx46fblCFE862bSx7z/pJ4FXpFRegMtJt6rDzlJCtT85mY/+ve29Tm+qQDBydijgqxJfg4mQMAiXFhM38ZxSSQAM91IcY/K/JNXZafARb+egPJQ8zbQtA4eNjBGsX4mqSMXmnnXzueuogVxn/ivbU7PetQL8U5tK9X0HBPxj9GcE5XCoNAJNQQh88wJKoRNs18qhnew4fqeiORdOUmcyCTn6pVuthWeHPVlVefJIEQtcxzk+W08ynfYY9LGwe7e+thB0Dg9HJSEjSMTkCyds6v4CKAD5uFfpdj0XYfDPLghSIlD/YXfoIg7lMQFBP7mUdBdaepsWotV5pp7f0YLPJ39Hpa3XPKCF+tN1oc2tbPLujWFwwJl8kWh0e+0DKf/AEJEAwdpO8n0GjrF5JpN3ZirZ/OQqRoH+l5gNPNlNsEsgHDM6AhughoosXxdRsCC4o/DmoI160SFhXbgY3eWEmfZ/ypxYheGgzvjk=
